name: Django CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        python-version: [3.5, 3.7]
    
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASS }}
          POSTGRES_HOST: ${{ secrets.DB_HOST }}

        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5
        
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: psycopg2 prerequisites
        run: sudo apt-get install libpq-dev gcc
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r web/requirements.txt
          pip install pytest-django
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASS }}
          POSTGRES_HOST: ${{ secrets.DB_HOST }}
      - name: Check migrations
        run: python web/manage.py makemigrations
      - name: Run migrations
        run: python web/manage.py migrate
        env:
          SECRET_KEY: ${{ secrets.DB_SECRET_KEY }}
      - name: Run tests
        run: py.test


